name: 'upgrade-brew-tap'
description: 'Get started with Container actions'
author: 'GitHub'
inputs: 
  name:
    description: 'brew tap name'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.myInput }}
