name: 'upgrade-brew-tap'
description: 'Get started with Container actions'
author: 'GitHub'
inputs: 
  myInput:
    description: 'Input to use'
    default: 'world'
runs:
  using: node12
  entrypoint: "entrypoint.sh"
